### ISSUE TITLE
Detect possible routes and determine which is in use

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider-monroe#1]
MONROE nodes can have multiple interfaces, we should detect which interface is the default route and record metadata for it, like the public IP that's seen, ASN, etc.

**Comment by irl** [comment]
Fixed in 95d735ce.

Not sure if we can do this Netfilter magic on MONROE though, need to check.

**Comment by ana-cc** [comment]
No 'Netfilter magic' possible, current code uses IPDB() to determine which route is used. Metadata still needs recording.

**Comment by ana-cc** [comment]
The default route is now programatically set at runtime.
