### ISSUE TITLE
multispider: Need to listen for NEWROUTE messages and invalidate if invalidated

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider-monroe#4]
The interface in use should not be going down during an experimental run, if that happens, the run should be aborted and the results invalidated.

If later it turns out that this happens a lot, we should look at more fine-grained invalidation, but hopefully that shouldn't be necessary.

**Comment by ana-cc** [comment]
Closing, added a callback function that works by listening for linkdown messages and matches against a global variable 'ifname'
